annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/policy-reporter:3.9.0-11.3
      name: policy-reporter
    - image: dp.apps.rancher.io/containers/policy-reporter-ui:2.7.1-11.11
      name: policy-reporter-ui
    - image: dp.apps.rancher.io/containers/policy-reporter-kyverno-plugin:0.7.0-11.3
      name: policy-reporter-kyverno-plugin
    - image: dp.apps.rancher.io/containers/policy-reporter-trivy-plugin:0.5.0-11.3
      name: policy-reporter-trivy-plugin
    - image: dp.apps.rancher.io/containers/trivy:0.74.0-16.4
      name: trivy
  license: MIT
apiVersion: v2
appVersion: 3.9.0
description: Policy Reporter adds observability and monitoring possibilities to your
  cluster security based on the PolicyReport CRDs.
home: https://apps.rancher.io/applications/policy-reporter
icon: https://apps.rancher.io/logos/policy-reporter.png
maintainers:
- name: SUSE LLC
  url: https://www.suse.com/
name: policy-reporter
version: 3.9.1
