# 02-kubewarden/secret-pull.yaml
apiVersion: v1
kind: Secret
metadata:
  name: application-collection
  namespace: cattle-kubewarden-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "dp.apps.rancher.io": {
          "username": "hhagenrud@suse.com",
          "password": "dHVxcXFqb2RhZG96a2l6Z2hmc3JhbWdheGV5aGJxaWVtbXZrbG5sbGlxYmRxcHFramdwamJ0dXJ6ZXNmaWdoeg==",
          "auth": "<base64(username:token)>"
        }
      }
    }