# 02-kubewarden/values.yaml

kubewarden-controller:
  enabled: true

# 2. Enable default PolicyServer creation
defaults:
  enabled: true

# 3. Disable telemetry collector if OpenTelemetry Operator is not installed
telemetry:
  metrics: false