# 02-kubewarden/values.yaml

# Disable telemetry metrics collector if OpenTelemetry operator is not in the cluster
telemetry:
  metrics: false

# 02-kubewarden/values.yaml
global:
  cattle:
    systemDefaultRegistry: "dp.apps.rancher.io"

# Passes the imagePullSecret to pods spawned by the controller
imagePullSecrets:
  - name: application-collection